#!/usr/bin/env python
# -*-python-*

import sys
import logging
import os.path
import mapzen.whosonfirst.git

if __name__ == '__main__':

   import optparse
   opt_parser = optparse.OptionParser()

   opt_parser.add_option('--start-commit', dest='start_commit', action='store', default=None, help='')
   opt_parser.add_option('--stop-commit', dest='stop_commit', action='store', default=None, help='')

   opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
   options, args = opt_parser.parse_args()
   
   if options.verbose:	
      logging.basicConfig(level=logging.DEBUG)
   else:
      logging.basicConfig(level=logging.INFO)

   whoami = os.path.abspath(sys.argv[0])
   whatami = os.path.basename(whoami)

   start_commit = options.start_commit
   stop_commit = options.stop_commit

   if start_commit:

      if not stop_commit:
         last_commit = mapzen.whosonfirst.git.get_current_hash()
         stop_commit = last_commit

      logging.info("invoking git-whosonfirst-mapzen %s hooks for %s - %s" % (whatami, start_commit, stop_commit))

   else:

      last_commit = mapzen.whosonfirst.git.get_current_hash()
      logging.info("invoking git-whosonfirst-mapzen %s hooks for whatever is different from %s" % (whatami, last_commit))

   files = mapzen.whosonfirst.git.get_diff(start_commit, stop_commit)

   for f in files:
      print f

   sys.exit(0)
